// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIcrV7zbwPoZzBsl_qQYNny1cO68Qggp0',
    appId: '1:448836335058:web:2b6de062e76fec2caf440b',
    messagingSenderId: '448836335058',
    projectId: 'myauthapp-1118c',
    authDomain: 'myauthapp-1118c.firebaseapp.com',
    storageBucket: 'myauthapp-1118c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGYd8eFalziEX8lnIPKSjEN1tHmv1b5mw',
    appId: '1:448836335058:android:ea1e41720f8444d4af440b',
    messagingSenderId: '448836335058',
    projectId: 'myauthapp-1118c',
    storageBucket: 'myauthapp-1118c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqr75JO5pgrt5bKSXUe4gLXAybGhEL4Ek',
    appId: '1:448836335058:ios:ba11ca4e91e0ed36af440b',
    messagingSenderId: '448836335058',
    projectId: 'myauthapp-1118c',
    storageBucket: 'myauthapp-1118c.appspot.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqr75JO5pgrt5bKSXUe4gLXAybGhEL4Ek',
    appId: '1:448836335058:ios:a5df825cd1818ce5af440b',
    messagingSenderId: '448836335058',
    projectId: 'myauthapp-1118c',
    storageBucket: 'myauthapp-1118c.appspot.com',
    iosBundleId: 'com.example.flutterApplication5.RunnerTests',
  );
}
